"""New Migration

Revision ID: 379b52918bd7
Revises: a6e4fafd1e6b
Create Date: 2021-02-27 12:50:11.238685

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '379b52918bd7'
down_revision = 'a6e4fafd1e6b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('group', 'joincode')
    op.create_foreign_key(None, 'user', 'group', ['group_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.add_column('group', sa.Column('joincode', sa.VARCHAR(length=10), nullable=False))
    # ### end Alembic commands ###
