"""Migration232

Revision ID: 3f221834ea49
Revises: af2653030a34
Create Date: 2021-03-07 23:08:22.584675

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3f221834ea49'
down_revision = 'af2653030a34'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('file', 'fileuploaded',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.LargeBinary(),
               nullable=True)
    op.alter_column('group', 'joincode',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.String(length=20),
               existing_nullable=False)
    op.create_foreign_key(None, 'user', 'group', ['group_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.alter_column('group', 'joincode',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=10),
               existing_nullable=False)
    op.alter_column('file', 'fileuploaded',
               existing_type=sa.LargeBinary(),
               type_=sa.VARCHAR(length=20),
               nullable=False)
    # ### end Alembic commands ###
