"""Initial

Revision ID: b85566cfde4e
Revises: a612e2773a8d
Create Date: 2021-03-01 22:06:33.251669

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b85566cfde4e'
down_revision = 'a612e2773a8d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('files', sa.String(length=20), nullable=True))
    op.create_foreign_key(None, 'user', 'group', ['group_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_column('task', 'files')
    # ### end Alembic commands ###
