"""3

Revision ID: c6ffe9dc2f76
Revises: b678cb581f3c
Create Date: 2021-03-07 15:27:29.030583

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c6ffe9dc2f76'
down_revision = 'b678cb581f3c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comment', sa.Column('group_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'comment', 'group', ['group_id'], ['id'])
    op.create_foreign_key(None, 'user', 'group', ['group_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_constraint(None, 'comment', type_='foreignkey')
    op.drop_column('comment', 'group_id')
    # ### end Alembic commands ###
