"""Initial migration.

Revision ID: c8911b9c076f
Revises: de05a70d594b
Create Date: 2021-02-28 16:23:09.796060

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "c8911b9c076f"
down_revision = "de05a70d594b"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, "user", "group", ["group_id"], ["id"])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "user", type_="foreignkey")
    # ### end Alembic commands ###
