"""Migration232

Revision ID: eba8d97e9724
Revises: b9bcf6f85d67
Create Date: 2021-03-07 22:35:50.950908

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eba8d97e9724'
down_revision = 'b9bcf6f85d67'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('file', sa.Column('image_file', sa.String(), nullable=False))
    op.alter_column('file', 'fileuploaded',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.alter_column('group', 'joincode',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.String(length=20),
               existing_nullable=False)
    op.create_foreign_key(None, 'user', 'group', ['group_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.alter_column('group', 'joincode',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=10),
               existing_nullable=False)
    op.alter_column('file', 'fileuploaded',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.drop_column('file', 'image_file')
    # ### end Alembic commands ###
